#########################
# Model Configurations  #
#########################

ROOT: '/srv/data/ltcl/data'
LOG: '/srv/data/ltcl/log'
DATASET: 'da_20'

SPLINE:
    USE_WARM_START: TRUE
    TYPE: 'gaussian'
    STEPS: 5000
    LR: 0.001
    CUDA: FALSE
    BS: 64
    LATENT_DIM: 4
    BOUND: 5
    BINS: 8
    ORDER: 'linear'
    PATH: '/srv/data/ltcl/ckpts/da_gau.pth'
  
VAE:
    GPU: [0]
    CPU: 8
    TRAIN_BS: 32
    VAL_BS: 5000
    EPOCHS: 200
    N_VAL_SAMPLES: 5000
    NCLASS: 20
    LR: 0.002
    BETA: 2.0e-3
    GAMMA: 2.0e-3
    SIGMA: 1.0e-6
    INPUT_DIM: 8
    CONTENT_DIM: 4
    STYLE_DIM: 4
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE

MCC:
    FREQ: 0.5
    CORR: 'Pearson' # 'Spearman'